import type { Metadata } from "next";
import { SidebarDashboard } from "./(private)/_components/sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SidebarDashboard>{children}</SidebarDashboard>
      </body>
    </html>
  );
}
